### ISSUE TITLE
Storage component not yet supported

### ISSUE THREAD

**Issue by BeccyGitHub** [WISPO-POP/PowerPlots.jl#122]
Hi, could you tell me how difficult it is to adapt the code to plot storage nodes (also for multinetworks)? What functions I would have to modify? Best

**Comment by noahrhodes** [comment]
Adding a single component is fairly straightforward.  You should look for any functions and constants with `gen_*` or `*_gen` in the name, and and those functions for `storage_`

This includes the function `storage_plot`, and parameters like `storage_color`, `storage_size`, `storage_data`, `storage_data_type`, along with defaults values for these parameters in the `default_plot_attributes` dictionary. 


I will also say that I hope to update powerplots to be able to support arbitrary components with just supplying the types of components that are nodes and edges respectively.  However, I do not know when I will have the time to do.

**Comment by BeccyGitHub** [comment]
All right, thank you!
