### ISSUE TITLE
data verification for vegalite

### ISSUE THREAD

**Issue by noahrhodes** [WISPO-POP/PowerPlots.jl#25]
Vega Lite does report errors when it doesn't work, it just won't do anything. This makes it hard to debug.

Checks should be added to make sure that the data/plot attributes are valid.

- Does a data column exist in the input data?
- Is a color a valid CSS3 color?

Add other data checks below...

**Comment by noahrhodes** [comment]
Memento sikence:
https://github.com/lanl-ansi/PowerModels.jl/blob/e0f0873374f13dd47a6be2ae87c0d7f9c17eec7e/src/PowerModels.jl#L26

Erro:
https://github.com/lanl-ansi/PowerModels.jl/blob/b569b2e7927bb672ff10d46c6e40195022686177/src/core/objective.jl#L26

**Comment by bryanluu** [comment]
@noahrhodes Is it okay if I delay this until next week? I've got a midterm this Fri (March 5) that I'd like to focus on, but am keen to get this implemented after!

**Comment by bryanluu** [comment]
@noahrhodes can you give me a list of invalid/valid data? For colors, is it a string representing the CSS color? Or symbol? I guess I'm just a little confused about what valid data should look like

**Comment by bryanluu** [comment]
Preliminary first implementation: [data_verification branch](https://github.com/WISPO-POP/PowerPlots.jl/tree/data_verification)

**Comment by noahrhodes** [comment]
Closed by #31
