### ISSUE TITLE
Add transformed coordinates

### ISSUE THREAD

**Issue by noahrhodes** [WISPO-POP/PowerPlots.jl#96]
In a pre-processing step 

- [x] Find max x/y coordinates
- [ ] set axis scale domain (possibly use small padding past max extent)
- [ ] Calculate a transformation for 'true' coordinates using the plot width/height and axis scale domains and store

**Comment by bryanluu** [comment]
What did we mean by the second step again @noahrhodes? What steps did we take, do you remember?

**Comment by noahrhodes** [comment]
I believe that the second step was about setting the length of the axis (so that you can use it to calculate the angle.
